#!/bin/bash
# Concatenate header + probes into suite-bundle.js for a single wasm module.
set -eu
here="$(cd "$(dirname "$0")" && pwd)"
out="$here/suite-bundle.js"
count=$(ls "$here"/probes/*.js | wc -l | tr -d ' ')

{
  cat <<HDR
// suite-bundle: generated by build-suite.sh — do not edit.
var __suiteLog = typeof print === "function" ? print : console.log.bind(console);
var __suite = { pending: $count, fails: 0 };
globalThis.__report = {
  pass: (n) => __suiteLog("PASS " + n),
  fail: (n, d) => { __suite.fails++; __suiteLog("FAIL " + n + " - " + d); },
  skip: (n, w) => __suiteLog("SKIP " + n + " - " + w),
  done: (n, f) => {
    __suite.fails += f;
    __suite.pending--;
    __suiteLog("RESULT " + n + ": " + f + " failed");
    if (__suite.pending === 0) {
      __suiteLog("VERDICT: " + (__suite.fails ? "RED (" + __suite.fails + " failures)" : "GREEN"));
    }
  }
};
HDR
  for f in "$here"/probes/*.js; do
    echo "(function(){"
    cat "$f"
    echo "})();"
  done
} > "$out"
echo "wrote $out ($count probes)"
